### ISSUE TITLE
TypeError wallet.py

### ISSUE THREAD

**Issue by Aareon** [yoyocoin/yoyocoin#20]
```
Traceback (most recent call last):
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/run.py", line 13, in <module>
    main()
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/run.py", line 9, in main
    m.run()
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/manager.py", line 24, in run
    block = self.actor.forge_block()
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/actor.py", line 75, in forge_block
    block = self.blockchain.create_unsigned_block(self.wallet.address)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/wallet.py", line 29, in address
    return b64encode(self.verifying_key.to_string(encoding="compressed")).decode()
TypeError: to_string() got an unexpected keyword argument 'encoding'
```
I’ll have to look but I’ve never seen an encoding used when converting an `ecdsa` verifying key to string.

**Comment by Aareon** [comment]
Looks like `to_string()` doesn’t take keyword arguments, but `to_string(“compressed”)` should work

**Comment by Aareon** [comment]
```
xception in thread client to ('127.0.0.1', 1818):
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/19A59DD1-D33D-41A3-A8D9-284E8B2E0222/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/netp2p/client.py", line 46, in run
    self.processor.process(msg)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/netp2p/processor.py", line 35, in process
    reply = msg_obj.process(self.chain, self.node)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/netp2p/messages/new_block.py", line 16, in process
    blockchain.add_block(self.block)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/chain.py", line 112, in add_block
    self.next_block_chooser.scan_block(block)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/next_block_chooser.py", line 29, in scan_block
    self.chain.validate_block(block)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/chain.py", line 227, in validate_block
    required_index=self._last_block_index + 1,
blockchain.exceptions.NonSequentialBlockError: Message: Block index is not sequential, Arguments: {'current_index': 2, 'required_index': 1}
```

**Comment by Aareon** [comment]
This came before the above exception

```
Exception in thread client to ('127.0.0.1', 1818):
Traceback (most recent call last):
  File "/var/containers/Bundle/Application/19A59DD1-D33D-41A3-A8D9-284E8B2E0222/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/netp2p/client.py", line 46, in run
    self.processor.process(msg)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/netp2p/processor.py", line 35, in process
    reply = msg_obj.process(self.chain, self.node)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/netp2p/messages/new_block.py", line 16, in process
    blockchain.add_block(self.block)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/chain.py", line 112, in add_block
    self.next_block_chooser.scan_block(block)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/next_block_chooser.py", line 29, in scan_block
    self.chain.validate_block(block)
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/chain.py", line 233, in validate_block
    if not block.signature_verified():
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/block.py", line 82, in signature_verified
    self.verifying_key, self.signature, self.hash  # type: ignore
  File "/private/var/mobile/Library/Mobile Documents/iCloud~com~omz-software~Pythonista3/Documents/Pythonista/Yoyocoin/src/blockchain/verifier.py", line 16, in is_verified
    b64decode(verifying_key_str), curve=Config.curve, hashfunc=Config.hashfunc
  File "/var/containers/Bundle/Application/19A59DD1-D33D-41A3-A8D9-284E8B2E0222/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/site-packages/ecdsa/keys.py", line 38, in from_string
    (len(string), curve.verifying_key_length)
AssertionError: (33, 64)
```
